// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBveZzrUK4_vDKiNRMwPAyhvV7qoTHuOs0',
    appId: '1:284461780920:web:37e9b34ea7440fea56c94d',
    messagingSenderId: '284461780920',
    projectId: 'istellacd',
    authDomain: 'istellacd.firebaseapp.com',
    storageBucket: 'istellacd.firebasestorage.app',
    measurementId: 'G-0QLR0FN818',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBveZzrUK4_vDKiNRMwPAyhvV7qoTHuOs0',
    appId: '1:284461780920:android:ANDROID_APP_ID',
    messagingSenderId: '284461780920',
    projectId: 'istellacd',
    authDomain: 'istellacd.firebaseapp.com',
    storageBucket: 'istellacd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBveZzrUK4_vDKiNRMwPAyhvV7qoTHuOs0',
    appId: '1:284461780920:ios:IOS_APP_ID',
    messagingSenderId: '284461780920',
    projectId: 'istellacd',
    authDomain: 'istellacd.firebaseapp.com',
    storageBucket: 'istellacd.firebasestorage.app',
    iosBundleId: 'com.stellamaris.istella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBveZzrUK4_vDKiNRMwPAyhvV7qoTHuOs0',
    appId: '1:284461780920:macos:MACOS_APP_ID',
    messagingSenderId: '284461780920',
    projectId: 'istellacd',
    authDomain: 'istellacd.firebaseapp.com',
    storageBucket: 'istellacd.firebasestorage.app',
    iosBundleId: 'com.stellamaris.istella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBveZzrUK4_vDKiNRMwPAyhvV7qoTHuOs0',
    appId: '1:284461780920:windows:WINDOWS_APP_ID',
    messagingSenderId: '284461780920',
    projectId: 'istellacd',
    authDomain: 'istellacd.firebaseapp.com',
    storageBucket: 'istellacd.firebasestorage.app',
  );
}
